### ISSUE TITLE
Full privilege user can't create a new VM

### ISSUE THREAD

**Issue by josselin-c** [vatesfr/xo-server#104]
Using xo-server next-release (94ba20df) or master 4.7.0 it appears I can't create a new VM using a user.

To reproduce:
1- User creation
From an admin account I create a user account (permissions: user) then I go to the ACLs page. 
There I select the user, for "objects" I select everything and for "role" I select Admin.
2- VM Creation
From the user account, I go to the pool page and click on "Add VM". There I select a debian template, the ISO image and I remove the disk and the network interface.
Pressing "Create VM" I get an error notification.

In the xo-server logs I get:
```Unauthorized: not authenticated or not enough permissions```

In the checkPermission method, If I print the permission and user variables before the exception is raised, I get:
```
xo-server[5364]: permission>>> admin
xo-server[5364]: user>>> User {
xo-server[5364]: domain: null,
xo-server[5364]: _events: {},
xo-server[5364]: _eventsCount: 0,
xo-server[5364]: _maxListeners: undefined,
xo-server[5364]: properties:
xo-server[5364]: { permission: 'none',
xo-server[5364]: email: 'user@account.com',
xo-server[5364]: pw_hash: '$myhash',
xo-server[5364]: groups: [],
xo-server[5364]: id: '2' } }
```

**Comment by olivierlambert** [comment]
That's a good question @josselin-c 

In both a bug and a feature. We aim to give user the right to create VMs, but our concern is to do it in a limited set of resources. It's possible to remove some perms for user with admin right to create VM, **but** it opens the door for uncontrolled resources usage. This said, it could be a first step before a real self-service portal. Is this portal should be independent from current VM creation view? I don't know yet.

**Comment by olivierlambert** [comment]
Will be solved by https://github.com/vatesfr/xo-web/issues/285, which is currently developed as we speak.
