### ISSUE TITLE
json5 in devDependencies

### ISSUE THREAD

**Issue by olivierlambert** [vatesfr/xo-server#109]
Each time I try to start `xo-server` globally, I got:

`Error: Cannot find module 'json5'`

That's probably because it's not a devDep anymore...

**Comment by julien-f** [comment]
Indeed, it should not be a dev dep, feel free to fix it.

**Comment by olivierlambert** [comment]
Do I have to do it manually or there is a npm command to execute?

**Comment by julien-f** [comment]
You can move it manually or uninstall it and reinstall it as a dev dep with
npm.
