### ISSUE TITLE
Possibility to serve on subdirectory

### ISSUE THREAD

**Issue by Phlogi** [vatesfr/xo-server#113]
Please add a way to make the http server resepect a base URL that can be appended to the server, like: mydomain.com/**xo-admin/**

**Comment by julien-f** [comment]
It should be working but it seems to be broken, I am on it.

**Comment by julien-f** [comment]
What is you configuration?
Why do you need this?
Do you have a reverse proxy?

**Comment by Phlogi** [comment]
xo-admin running on a seperate vm and having a reverse proxy on another machine, in my case the firewall that should server xo-web as a subfolder rather than having a subdomain. It's pretty specific but when you look at most of todays web apps, they allow to set a base_folder or web_root that is respected when serving the app. 

For the moment I can implement the remote access by using a subdomain, but I think the option should be there.

**Comment by Phlogi** [comment]
.. I assume this will be implemented in https://www.npmjs.com/package/http-server-plus? From my research this feature would benefit other projects as well.

**Comment by julien-f** [comment]
It should already be working, there are no needs to configure it, what is the issue?

**Comment by Phlogi** [comment]
So how would I configure it then?

**Comment by julien-f** [comment]
You should find what you need in the documentation: https://github.com/vatesfr/xo/tree/master/doc/recipes :)

**Comment by Phlogi** [comment]
Well, what if the the location is not / but more like: 

location /subfolder {

Would xo-web still work - I will try it out and report back.

**Comment by julien-f** [comment]
Il should.
Once you confirm it, I will make it clearer in the docs :)

**Comment by Phlogi** [comment]
It's worth referencing this here: 
https://github.com/indexzero/http-server/issues/139#issuecomment-153494297

**Comment by Phlogi** [comment]
As expected, it doesn't work, even when I use the appropriate redirect directives:


                location /xen {
                        #include proxy_common.conf;
                        proxy_http_version 1.1;
                        proxy_set_header Upgrade $http_upgrade;
                        proxy_set_header Connection "upgrade";
                        rewrite /xen/(.*) /$1 break;
                        proxy_pass https://IP:443/;
                        proxy_redirect https://IP https://pub.domain/xen;
                }

Because the redirect to /login fails, it returns https://pub.domain/login instead of ttps://pub.domain/xen/login.

**Comment by julien-f** [comment]
Try with a trailing slash: `https://pub.domain/xen/`, hopefully it will work.

**Comment by julien-f** [comment]
> It's worth referencing this here:
> indexzero/http-server#139 (comment)

I don't see the relation.

**Comment by Phlogi** [comment]
I thought that the webserver of xo-web is based on http-server, that's why I referenced it.

**Comment by julien-f** [comment]
I see :)

No, it's not, it's based on [http-server-plus](https://github.com/julien-f/http-server-plus/) which is a small layer on top on native Node's HTTP implementation.

**Comment by Phlogi** [comment]
It doesn't work, even with the trailing /. What about all the relative paths on inside the web application, they would point to non existing paths like: https://pub.domain/assets or whatever there is.

**Comment by julien-f** [comment]
I am installing and testing nginx right now, I'll keep you posted.

**Comment by Phlogi** [comment]
Thanks a lot, for some applications it works, for some it doesn't - depends on the paths inside the markup for example. Anyway best would be to have a base_root in xo configuration like many applications offer. 

http://superuser.com/questions/689885/make-nginx-reverse-proxy-302-redirect-to-a-uri-sub-folder-instead-of-root

**Comment by julien-f** [comment]
Sorry for not understanding your problem sooner, there is indeed an issue in xo-server which will be fixed in the next release (next week).

I also updated the [documentation for nginx](https://github.com/vatesfr/xo/blob/master/doc/recipes/nginx-reverse.md).

I think you might get the current version to work by using the following settings in your nginx configuration:

```nginx
location /xen/ {
  proxy_pass https://IP:443/;

  proxy_http_version 1.1;
  proxy_set_header Connection "upgrade";
  proxy_set_header Upgrade $http_upgrade;

  proxy_redirect / /xen/;
  proxy_redirect ../.. /xen/;
}
```

**Comment by Phlogi** [comment]
It doesn't work, the redirect is still not correct. I ended up using a subdomain for now.

**Comment by julien-f** [comment]
Hmm weird...

Would you mind to retry when the next version will released?

**Comment by Phlogi** [comment]
Sure, I would.

**Comment by olivierlambert** [comment]
@Phlogi : did it change anything?

**Comment by Phlogi** [comment]
I haven't tested it yet, would I need to set the subdomain in the xo-server config or just use the redirect settings in nginx?

**Comment by julien-f** [comment]
The goal is to have nothing to configure :)

**Comment by olivierlambert** [comment]
@Phlogi closing it but feel free [to create a new issue here](https://github.com/vatesfr/xo-web/issues/new) if you still experience the issue :)
