### ISSUE TITLE
Issues with config.json

### ISSUE THREAD

**Issue by rtgibbons** [vatesfr/xo-server#151]
`config.json` is loaded at runtime and can't contain comments `//` as JSON doesn't have a comment notation.

Also while investigating this I've noticed that you are defining `verboseApiLogsOnErrors`, but the code looks to use `verboseLogsOnErrors`

**Comment by julien-f** [comment]
`config.json` is parsed with [json5](https://www.npmjs.com/package/json5) which supports comments.

And [you are not supposed to edit this file directly](https://github.com/vatesfr/xo-server/blob/next-release/config.json#L1-L3) :)

**Comment by rtgibbons** [comment]
Yeah I knew that, couldn't figure out though why it would start though.

It was missing the json5 package, it missing a lot of packages actually. `npm install` and all is well.
