### ISSUE TITLE
Xo-server doesn't start

### ISSUE THREAD

**Issue by gelato** [vatesfr/xo-server#202]
I've updated the server and the web to the latest version on next-release branch and now it doesn't start, showing me this error:

> xo-server@4.11.0 start /home/holder/xo-server
> node bin/xo-server

/home/holder/xo-server/dist/decorators.js:1
n']){_iterator4['return']();}}finally {if(_didIteratorError4){throw _iteratorE
                                                                    ^
Error: Xo.arguments is already defined
    at /source/decorators.js:300:14
    at /source/xo.js:76:21
    at Object.<anonymous> (/source/xo.js:76:23)
    at Object.<anonymous> (/source/index.js:37:32)
    at Object.<anonymous> (/home/holder/xo-server/index.js:11:18)
    at Object.<anonymous> (/home/holder/xo-server/bin/xo-server:13:25)

npm ERR! Linux 3.2.0-4-amd64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! xo-server@4.11.0 start: `node bin/xo-server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the xo-server@4.11.0 start script 'node bin/xo-server'.
npm ERR! This is most likely a problem with the xo-server package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node bin/xo-server
npm ERR! You can get their info via:
npm ERR!     npm owner ls xo-server
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/holder/xo-server/npm-debug.log

Is there a way to fix this?

**Comment by julien-f** [comment]
Please, provide the result of the command line `npm version`.

**Comment by gelato** [comment]
{ 'xo-server': '4.11.0',
  npm: '2.11.3',
  http_parser: '2.3',
  modules: '14',
  node: '0.12.7',
  openssl: '1.0.1p',
  uv: '1.6.1',
  v8: '3.28.71.19',
  zlib: '1.2.8' }

System is Debian 7

**Comment by julien-f** [comment]
I am going to do some tests but I believe there might be an issue with xo-server regarding Node 0.12, you can try with Node 4 which is the new LTS.

**Comment by julien-f** [comment]
Will ship in Xo 4.12.

**Comment by gelato** [comment]
Thx )
