### ISSUE TITLE
Change name for replication snapshot to avoid conflict

### ISSUE THREAD

**Issue by buzzzo** [vatesfr/xo-server#226]
Naming the snapshot as the vm_name cause problem with third party backup tool like naubackup.
Naubackup checks if the base vm_name is unique, and exit if it finds more than one entity with this name.

In case of a vm under replication it ALWAYS find because the replication task keep the snapshot with the name of the vm itself.

Would be better to call the snapshot something like REPL_vm_name or something like that

**Comment by olivierlambert** [comment]
@julien-f I think we already fixed that for the coming release, can you confirm?

**Comment by julien-f** [comment]
Yes, the snapshots are called (for now) `XO_DELTA_EXPORT: <name of destination SR> (<UUID of destination SR>)`.
