### ISSUE TITLE
Add ability to fill user groups from ldap

### ISSUE THREAD

**Issue by dawidmalina** [vatesfr/xo-server#234]
It would be nice if we could fill user groups from ldap.

**Comment by julien-f** [comment]
You mean create each LDAP groups a user is in when it signs in?

Should the group names be prefixed by `ldap:`?

**Comment by julien-f** [comment]
With current architecture, it should not be difficult to create XO groups from LDAP groups on user sign in but they would be separate groups and not synchronized in any way: adding/removing a user from an LDAP group would not propagate into XO.

**Comment by dawidmalina** [comment]
When user login ldap is also returning groups (in which user is). What it would be nice to grab this groups and match according configured ACL.

For example:
- user Bob is in group xo-operator
- user John is in group xo-admin

Then I can configure proper ACL to match xo-operator as operator role and xo-admin to match admin role.

**Comment by julien-f** [comment]
That's quite interesting but I see potential security issues (which could be mitigated by having a fixed list of valid groups in the plugin config for instance) and synchronizing LDAP groups with XO groups may not be trivial:

**What happens if the LDAP user has a group the XO user has not?**
> Automatically create the XO group and add the user inside.

**What happens the LDAP user is removed from a group it was in?**
> ??

**Comment by dawidmalina** [comment]
I can tell how does it looks in Jira or Confluence or Jenkins.
Ldap is source of truth (app have only local cache to make sure we will not hit Ldap over and over). If user exist in ldap user can be authenticated via ldap and can login but don't see anything (this is what we have now in xo).

If user is in group jira-users then such user can login into jira as regular user. If user is in group jira-administrators then such user can login into jira and have admin rights.

Groups are created automaticly (user can be in more then one group) but only static maping is needed -  group and privileges for this group (in our case we should define only this mapping on xo side).

Check this section: https://confluence.atlassian.com/doc/connecting-to-an-ldap-directory-229838241.html

So we should not define any users and groups in xo. All users and groups should be retrieved from Ldap. If user groups will be changed in Ldap xo after cache timeout will reload this info from Ldap and in worse scenario user will not be able to login or will lose admin privileges.
So

**Comment by tbe** [comment]
I have done this in the last days.

https://github.com/BundesIT/xo-server-ldap-plus

There are still some issues with the group management, but it is usable.

**Comment by julien-f** [comment]
This issue was moved to vatesfr/xo-web#1884
