### ISSUE TITLE
The 'npm build run' fails after 'npm install --production'

### ISSUE THREAD

**Issue by bartekrutkowski** [vatesfr/xo-server#239]
The development dependencies are listing gulp, but production ones don't. When deps installation is done with `npm install --production` then the following `npm run build` fails with not being able to find gulp (Ansible task output):

```
fatal: [xoa-dev.hub]: FAILED! => {
  "changed": true,
  "cmd": "npm run build --progress=false --production",
  "delta": "0:00:01.643239",
  "end": "2016-02-18 10:57:38.050029",
  "failed": true,
  "rc": 1,
  "start": "2016-02-18 10:57:36.406790",
  "stderr": "gulp: not found\n\nnpm ERR! FreeBSD 10.2-RELEASE-p9\nnpm ERR! argv \"/usr/local/bin/node\" \"/usr/local/bin/npm\" \"run\" \"build\" \"--progress=false\" \"--production\"\nnpm ERR! node v5.2.0\nnpm ERR! npm  v2.14.7\nnpm ERR! file sh\nnpm ERR! code ELIFECYCLE\nnpm ERR! errno ENOENT\nnpm ERR! syscall spawn\nnpm ERR! xo-server@4.13.0 build: `npm run build-indexes && gulp build --production`\nnpm ERR! spawn ENOENT\nnpm ERR! \nnpm ERR! Failed at the xo-server@4.13.0 build script 'npm run build-indexes && gulp build --production'.\nnpm ERR! This is most likely a problem with the xo-server package,\nnpm ERR! not with npm itself.\nnpm ERR! Tell the author that this fails on your system:\nnpm ERR!     npm run build-indexes && gulp build --production\nnpm ERR! You can get their info via:\nnpm ERR!     npm owner ls xo-server\nnpm ERR! There is likely additional logging output above.\n\nnpm ERR! Please include the following file with any support request:\nnpm ERR!     /usr/local/xoa/xo-server/npm-debug.log",
  "stdout": "\n> xo-server@4.13.0 build /usr/local/xoa/xo-server\n> npm run build-indexes && gulp build --production\n\n\n> xo-server@4.13.0 build-indexes /usr/local/xoa/xo-server\n> ./tools/generate-index src/api & ./tools/generate-index src/xo-mixins",
  "stdout_lines": [
    "",
    "> xo-server@4.13.0 build /usr/local/xoa/xo-server",
    "> npm run build-indexes && gulp build --production",
    "",
    "",
    "> xo-server@4.13.0 build-indexes /usr/local/xoa/xo-server",
    "> ./tools/generate-index src/api & ./tools/generate-index src/xo-mixins"
  ],
  "warnings": []
}
```

**Comment by julien-f** [comment]
It's because dev dependencies are required to build xo-server.

**Comment by bartekrutkowski** [comment]
Shouldnt then they've be in production dependencies instead of dev ones? I'd expect the prod ones to contain minimal set of deps to run XO on production, and dev ones to only be required in development environments.

**Comment by julien-f** [comment]
Nope, prod dependencies are only needed to run the software, dev dependencies are necessary to test and build it.

**Comment by bartekrutkowski** [comment]
But it isnt possible to run xo-server/web without building it first, right? So in the end, everyone needs to install without `--production` anyway, unless there's some other way that I am missing?

**Comment by julien-f** [comment]
In fact there is also an [already built package](https://www.npmjs.com/package/xo-server) on [npmjs.com](https://www.npmjs.com/) which can be installed directly with `npm` (it is still required to install [`vhd-util`](https://xen-orchestra.com/docs/from_the_sources.html#external-dependencies) manually though).

We prefer to promote installing from the sources because it's easier for people to contribute :)

**Comment by mxk** [comment]
I don't see any installation instructions related to vhd-util. Can you please elaborate on how that needs to be installed and where?

**Comment by julien-f** [comment]
It's because this dependency is no longer required since the latest version :)

**Comment by mxk** [comment]
Got it, thanks! By the way, the npmjs packages are still at version 4.13.

**Comment by julien-f** [comment]
I am on it :)

They are not regularly updated because I said before the accent is put on the sources (to attract contributions) or on the appliances.

**Comment by julien-f** [comment]
All published :)
