### ISSUE TITLE
VMs which failed to be created should not stay in templates list

### ISSUE THREAD

**Issue by julien-f** [vatesfr/xo-server#25]

**Comment by olivierlambert** [comment]
@julien-f do we made something about this or not? If not, I'm going to open an issue in the `xo-web` repo.

**Comment by julien-f** [comment]
Nope, it has not been fixed for now, it is much less pressing than before because the creation code is much more robust and failures are very rare.

**Comment by olivierlambert** [comment]
What do you suggest about this issue? I mean:

* moving it to main repo
* just closing it
* obiwan kenobi

**Comment by julien-f** [comment]
I am very much tempted to say *Obiwan Kenobi* but I believe it would be best to move it to the main repo :p

**Comment by olivierlambert** [comment]
Copy that.

https://github.com/vatesfr/xo-web/issues/708
