### ISSUE TITLE
Delta backup Depth not working

### ISSUE THREAD

**Issue by secretxhun** [vatesfr/xo-server#261]
Good Day!

I tested the delta backup, the restore is working :) , but the depth option is not working, i set to 3, and i have 47 vhd files on NFS, and size is 47* 30M instead of 3* 30M.
I use 4.14.1

Thanks, Andras

**Comment by olivierlambert** [comment]
Please open an issue on the "central" issue repo: https://github.com/vatesfr/xo-web/issues/new
