### ISSUE TITLE
can't create vm, or change memory size on stopped vm

### ISSUE THREAD

**Issue by cactus** [vatesfr/xo-server#269]
When I try to create a vm, I see this error in the log:

     | vm.create(...) [9ms] =!> InvalidParameters: invalid parameter(s)

I also get the same error in the log when attempting to change the memory or cpu count for a stopped vm, which also fails. I tried xo-server-logs to see if it would show more logging, but it just continually threw an error: `✖ fn is not a function`.

info:
* xo-server: `cbf4786b391dff4da936fe28e53075204011ac29`
* xo-web: `0eadfd5a58e5dff80f5152af682752dee5da61fa`
* node: `v5.9.0`
* os: `FreeBSD-10.3`
* xenserver: `6.5.0-90233c` (with all patches applied)

Sorry if this is reported to the wrong project. Hard for me to tell if the issue stems from the web component or the server component.

**Comment by cactus** [comment]
Wow. Disregard. I wasn't selecting a template (needed to pick "Other install"). Picking that template and it works fine now.

**Comment by olivierlambert** [comment]
Tip: try to stick to the LTS version of Node.

And the template picking should be mandatory in the interface, I'll check that on my side :)
