### ISSUE TITLE
Server crash when receiving incorrect WebSocket data

### ISSUE THREAD

**Issue by julien-f** [vatesfr/xo-server#27]
When the server receives a connection with incorrect WebSocket data (e.g. unsupported protocol version), it crashes with `Uncaught, unspecified "error" event`.

Probably related to this einaros/ws#246.

**Comment by olivierlambert** [comment]
Last comments gave a hack: https://github.com/websockets/ws/issues/246

Is it necessary or we could close this one @julien-f ?

**Comment by julien-f** [comment]
Let's close it for now, we'll reopen it if necessary.
