### ISSUE TITLE
continuos replication vm dst name

### ISSUE THREAD

**Issue by buzzzo** [vatesfr/xo-server#281]
On xo-server 4.15.2 during the vm import on the target node the vm name is not the src vm name but the 
uid of the snapshot.

**Comment by olivierlambert** [comment]
Can you give me the VM name verbatim?

**Comment by buzzzo** [comment]
The name is sqlserver2.gci.local.
In the image attached you could see two pool: the upper is the destination for the replication.
And you could see the vm named "snapshot of ..." that is the result of the replication process.

Note that sometimes the destination vm are named correctly (in this case: sqlserver2.

Thx 
![continuous_dr_snap](https://cloud.githubusercontent.com/assets/7355941/14635757/21b8b1c2-0628-11e6-9bc6-dcc43ebe1119.png)

**Comment by julien-f** [comment]
We have some clues about this issue, it may be related to snapshotting of Windows VM? we'll know more during the day.

**Comment by buzzzo** [comment]
Could be. Sometimes the (quescied) snapshot fails, but it's not directly related with the strange name.
