### ISSUE TITLE
 reattach sr bug

### ISSUE THREAD

**Issue by arjing** [vatesfr/xo-server#286]
forget a iscsi sr, when the sr is reattached, there is no host connected.
![qq 20160425104905](https://cloud.githubusercontent.com/assets/10625324/14772653/6864bad0-0ad3-11e6-9594-f8b8092f1762.png)

**Comment by olivierlambert** [comment]
Hi,

Thanks for the report. Because we are rewriting everything in the new xo-web for 5.0, this view will be re-created and tested. Thus, I let this issue open until we got something working in the new interface.

**Comment by olivierlambert** [comment]
@arjing can you make the test again with the new UI? Thanks!

**Comment by arjing** [comment]
1.when  specify  the iscsi   port . error is:
![1111qq 20160714170301](https://cloud.githubusercontent.com/assets/10625324/16834223/716efe8c-49e5-11e6-9f0f-eb91058dca24.png)
2.no iqn has been found.
![2222qq 20160714170323](https://cloud.githubusercontent.com/assets/10625324/16834475/86762d54-49e6-11e6-8042-96dd3de8949b.png)
![3333qq 20160714170343](https://cloud.githubusercontent.com/assets/10625324/16834498/a2af7c5a-49e6-11e6-92ef-f562fa0d7a2a.png)

**Comment by olivierlambert** [comment]
Indeed, saw the bug myself recently. We'll fix it! Thanks for your feedback :)

**Comment by olivierlambert** [comment]
Closing this one, recreated there: https://github.com/vatesfr/xo-web/issues/1281
