### ISSUE TITLE
MEMORY_CONSTRAINT_VIOLATION error when editing VM's

### ISSUE THREAD

**Issue by Fohdeesha** [vatesfr/xo-server#306]
Hi, I've gotten this error on two totally different installs now on two machines, both with orchestra built from sources. The machine a month ago started out with this error and something I did eventually remedied it, but now with another clean XenServer and Xen Orchestra install on a new machine, it's back.

When I go to edit a VM in the GUI, for instance changing auto power on or name or memory, or even just clicking the edit button and clicking save without changing anything, thew GUI gives an error that the action failed for unknown reason. Below is the actual output from XO when this happens, so it seems like an issue with how the memory field is populated or attempting to be adjusted.

I've attempted manually adjusting memory amount for the vm in XenCenter thinking this might make XO re-populate that field with a good value, but no luck. The VM's are set to "fixed memory" in the memory adjuster in XenCenter. Thanks! It's worth noting on both these installs absolutely everything else works great, installing patches, editing the hypervisor, backups, everything but this.

error output - http://pastebin.com/NUPGyytZ

XenServer version is the latest 6.5 SP1 fully patched as of 5/11/16

**Comment by Fohdeesha** [comment]
Progress....if I change the VM's memory type from "Fixed" to "Dynamic" in XenCenter, then I can succesfully edit VM properties in XO GUI such as "auto power on" without getting the above error, as long as I leave the memory box the same, so that's much better than not being able to edit anything. So it seems the dynamic memory adjustment API command XO uses by default isn't compatible with VM's configured with Fixed Memory.

However now, if I try to lower the memory amount in the XO GUI in the same VM properties panel (for instance lowering the 1.5gb value to 1.4gb), It doesn't work and XO spits out a slightly different error - http://pastebin.com/fNFPuiLQ

Thanks again! Loving XO so far

**Comment by olivierlambert** [comment]
This is because our UI doesn't expose memory constraint. If your VM is running, you can't change the RAM range outside the "dynamic" range.

So you'll have to power off the VM, and then you can change the values in XO. If the value is outside the static range, we'll extend it automatically.

We know that's not very satisfactory behavior, but it was the easiest one to implement. Obviously, we'll improve this.

**Comment by Fohdeesha** [comment]
Thanks for replying, that makes sense. Might I suggest in the meantime making the error message when changing these values something like "Cannot alter RAM outside of dynamic range when VM is running", or even not re-submitting the memory box value if it hasn't been changed, that way users can edit everything (like name and power on values) without it failing with a generic error because memory type is set to static and it's trying to re-submit the unchanged value while it's running? Thanks again!

**Comment by olivierlambert** [comment]
The new UI will handle this differently so the problem will disappear by itself ;)

**Comment by olivierlambert** [comment]
Duplicate of https://github.com/vatesfr/xo-web/issues/970
