### ISSUE TITLE
XO won't retain backed-up database upon Docker reboot

### ISSUE THREAD

**Issue by frebib** [vatesfr/xo-server#314]
Running XO in Docker using [this config](https://github.com/jpoa/docker-xo) by jpoa works just fine but when mounting the directories containing the XO configuration database in directories outside of the container then XO does not load the configs again after restarting or recreating the container.

To be clear, all of the config files [as explained here](http://mangolassi.it/topic/7611/xen-orchestra-backup-yourself) are available in the filesystem as normal but for some reason XO doesn't see them when it starts so maybe there are some other configs that I'm missing or something has changed (or I am using Docker wrong) but I can't seem to get it to keep the configuration.

I can create users, connect XO to Xen and work as normal. When rebooting the container, the files are written as normal but XO doesn't detect them and acts as if there are no database files present: all users and server connections are gone as would be in a clean XO install.

Thanks

**Comment by olivierlambert** [comment]
I'm not enough experienced in Docker, probably a environnement issue (the "working" dir visible from `xo-server` is not the right one to see those files). Just a supposition.

**Comment by frebib** [comment]
Sorry, I shouldn't make this about Docker because I'm pretty sure that's not the issue here. My problem seems to occur when keeping copies of the XO configuration across what are effectively different installations of XO. My aim is to back up exactly just the directories necessary to carry the database and whatever else from one XO install to another.

Which directories do I have to back up to facilitate this process? I tried just the ones noted in your post a few months back but it seemed to not work. 

I even tried including the dump.rdb file that is put in the XO folder presumably by `xo-server`. Bizarrely from what I could see, the database was empty and all data was stored in that dump file. Are there any specific requirements to ensuring xo-server writes all the data to the database correctly before stopping the process?

Thanks

**Comment by olivierlambert** [comment]
I think if you followed the recommandations given in the forum where I posted, it should work. Are you sure it's using the right files? Any log error or something like that? It's late here, maybe I'll see more clearly tomorrow.

**Comment by frebib** [comment]
I think so. Currently our Xen server isn't active but when we get it back up in a few days I'll try again. I didn't think of checking the node logs, I'll do that next time. Thanks for your help and I'll report back soon hopefully with some more information/results

**Comment by olivierlambert** [comment]
Sure! Keep me posted :)

**Comment by frebib** [comment]
We have moved away from Xen now, however a friend of mine managed to solve the issue.
Redis seems to cache it's data and not always write the database but editing the config for it made it behave a bit more.
For reference, here is his Dockerfile config for anyone wanting this functionality. https://github.com/Adam-Ant/docker-xo
