### ISSUE TITLE
Creating VM Fails with "ReferenceError: $isVmRunning is not defined"

### ISSUE THREAD

**Issue by Fohdeesha** [vatesfr/xo-server#319]
Running next-release XO from sources, with xenserver 6.5SP1, everything seems to work correctly except the creation of new VM's from the GUI. No matter what settings I use, I receive a "action failed" in the UI.

The only error I see in XO output is: 
vm.set(...) [5ms] =!> ReferenceError: $isVmRunning is not defined

before this error, it succesfully creates the storage and VIF's no problem. When I look in XenCenter, the VM is there successfully created, but not started and has the incorrect amount of memory. 

Should I stick to the stable branch when using 6.5? It has a couple bugs that drive me crazy, including the incorrect power-on value being stuck into my pool config that was reported a few days ago. Thankfully next-release solves this :)

it seems like the VM creation process is running the "$isVmRunning" xapi query when it shouldn't be as the VM obviously doesn't even exist yet

**Comment by olivierlambert** [comment]
We'll release a stable of `xo-server` very soon (tomorrow). About your issue, I'll check this ASAP.

Is it happening if you don't tick the "Boot VM on creation" checkbox?

**Comment by Fohdeesha** [comment]
Thanks for the fast reply! That's great news.

I just tried again without checking "boot on creation" and I still receive the same behavior and error message
