### ISSUE TITLE
Delta Backups Failing Randomly

### ISSUE THREAD

**Issue by Fohdeesha** [vatesfr/xo-server#336]
I've been using Delta Backups to an SMB share for a while, but recently, they mostly fail outright. If I keep one shotting them a few times eventually it will succesfully manage to backup one or two vm's but not all of them. It used to work perfect for all vm's with no issue. I'm on the next-release branch.

I'm witnessing this behavior on two seperate xenserver machines and XO installs, both 6.5sp1.

Here's some partial output of when it tries to run a backup and fails - http://pastebin.com/eVcQtngN

**Comment by olivierlambert** [comment]
Two thing:

* XenServer 6.5 has some issues with generating delta. XenServer 7 fixed it. I strongly suggest to upgrade
* Yours logs tell `Error: there is not object can be matched to OpaqueRef:4a453a7c-577a-8dcc-6430-4dcbd22646c6`: it means you are trying to backup a removed VM (or a VM on a host which isn't connected anymore)

**Comment by Fohdeesha** [comment]
Thanks for the fast reply. Thanks for the tip about 6.5 - is it an intermittent issue? It used to delta backup without any problems but then all the sudden it's having difficulty, very strange.

And I double checked and the vm's in the backup job definitely exist - in fact Ive never deleted a VM on this host. The host is definitely connected as well since it successfully backs up another VM in that job. Hmm

**Comment by olivierlambert** [comment]
* it's a random issue. However, I found a way to reproduce it somehow: more often you are asking for delta's, more likely XenServer will fail.
* the XO log tells an object with its ref can't be found, I don't know why. You should investigate further. For this, we have some tools: take a look here https://github.com/julien-f/js-xen-api#cli

**Comment by Fohdeesha** [comment]
Trying to avoid the delta issue temporarily, I deleted all delta backups and jobs and scheduled a full normal backup, and now it is failing as well and the log output says it can't find *any* of my vm's now, even though they definitely exist and have never been moved/deleted. I'm seeing this on another system as well. Did a recent push to next-release break all backup features on 6.5? I didn't have any of these issues until I ran an update last week sometime. I wish I could use the CLI tools to figure out more but it's definitely above my knowledge, I'm not much of a software guy :/ http://pastebin.com/ea8eGYSm

**Comment by olivierlambert** [comment]
1. Did you restart `xo-server`?
1. Is it the same on `stable` branch?
1. What's your version of `npm` and `node`?

**Comment by Fohdeesha** [comment]
I restarted xo-server, the vm it runs on, and the whole xenserver host it's trying to back up just to be sure.

npm is 3.8.9, node is 4.4.4

I haven't had a chance to switch to stable branch to test yet. I'm going to wipe my whole XO installation and start fresh and see if the problem persists.

I really appreciate all the help you give free users!

**Comment by Fohdeesha** [comment]
I have created a brand new VM and installed XO from scratch, this time the stable branch. Backups are working perfectly as expected. Later today I will move to next-release and see if it goes back to failing as before

**Comment by olivierlambert** [comment]
Thanks. If it's the case, we'll have a good clue and we'll be able to find the issue easily.

**Comment by Fohdeesha** [comment]
I switched to next-release branch and both full backups and delta backups are still working perfectly. I wonder why the other VM with XO was failing so much (and also another colocated host with an XO vm having the same issue)? Even after I flushed their Redis DB's and re-grabbed from the git repo and re-built, they were still failing. The only difference between those systems and this new test VM is that they have slightly older node and npm versions than the VM I set up last night, could that have done it?  (this new working install has Node v4.4.5 and NPM v3.9.6) 

The odd thing is some backups it would say it couldn't find certain vm objects, then running the same backup again 30 minutes later it finds it and backs up those objects no problem and then can't find different VM's it found before. I'm going to upgrade node and npm on the older VM's and see if anything changes. Thanks for the help!

**Comment by olivierlambert** [comment]
Thanks for the hints. Because we'll release this week, I'll make a full sweep on every features. So there is chances we found something (I hope). I'm keeping this issue open until we release.

**Comment by Fohdeesha** [comment]
Delta backups still working great after fixing the /var/lib corruption issue. I thought I'd ask a slightly related question here before this issue gets closed. What is the primary limiting factor on backup speed? 

I am doing Delta backups to a remote SMB share and there is 100mbps of bandwidth between the two (according to iperf). However when XO does the big initial Base transfer for the delta (some of my base  deltas on the SMB share are 100GB), it never goes over 15mbps or so, making it take quite a long time. I thought it might be CPU or memory related, so I checked the resources and usage on the hypervisor and XO VM, and they are barely being used. So where's the bottleneck? Thanks!

**Comment by olivierlambert** [comment]
It's mainly related to XAPI HTTP export speed. XenServer 7 made progress on that.

Could be also: SR read speed, SMB write speed. But in general it's related to XenServer/XAPI HTTP export. XOA by itself is just acting like a "proxy", and Node is really fast on I/O intensive workload.
