### ISSUE TITLE
Lodash modules missing from requirements for xo-server 5.0.0

### ISSUE THREAD

**Issue by bartekrutkowski** [vatesfr/xo-server#351]
When upgrading xo-server from 4.16 to latest 5.0 by deleting node_modules and running `npm install && npm run build` from properly refreshed xo-server sources directory (using `git pull --ff-only`), two lodash related modules are missing (namely lodash.every and lodash.includes), something that xo-server binary complains about when starting. After installation of the missing modules, the xo-server binary starts xen orchestra application properly.
The testing platform was FreeBSD 10.3-p5, with Node 6.2.1_3 and Npm 3.9.2.

**Comment by julien-f** [comment]
Try deleting `dist/` as well, it should fix your issue :)

**Comment by bartekrutkowski** [comment]
Shouldn't this step be added to the documentation then?

**Comment by julien-f** [comment]
I updated the build process to delete `dist/` before compiling, it should not happen again :)
