### ISSUE TITLE
Xen Orchestra v5.0.0 fails to login when using Safari 9.1.1 on OS X 10.11.5

### ISSUE THREAD

**Issue by bartekrutkowski** [vatesfr/xo-server#352]
Latest updated xen orchestra instance (manual git update and npm install/run build from 4.16 to 5.0) fails to log in users properly - a blue spinning wheel keeps spinning forever, while there seems to be nothing obviously wrong logged in output of xo-server process. The very same installation logs the same user just fine using Chrome 51.0.2704.84 on the very same OS X.

**Comment by julien-f** [comment]
Its probably related to vatesfr/xo-web#1120, if you want to use Safari, you should probably stick to xo-web 4 ATM.
