### ISSUE TITLE
remote mounts appears broken 

### ISSUE THREAD

**Issue by svkamp** [vatesfr/xo-server#367]
mount -t nfs vault.xxxxxx.com:/data/backup /tmp/xo-server/mounts/remote-4
mount: wrong fs type, bad option, bad superblock on vault.xxxxxxx.com:/data/backup,
       missing codepage or helper program, or other error
       (for several filesystems (e.g. nfs, cifs) you might
       need a /sbin/mount.<type> helper program)

       In some cases useful info is found in syslog - try
       dmesg | tail or so.
root@xoa:/home/dingo# ls /tmp/xo-server/
mounts
root@xoa:/home/dingo# ls /tmp/xo-server/mounts/
remote-2  remote-3  remote-4

**Comment by olivierlambert** [comment]
Hi,

Please open an [issue here](https://github.com/vatesfr/xo-web/issues/new), as explained [in the doc](https://xen-orchestra.com/docs/contributing.html#bug-reports). Because the issue template is very important for us to understand your issue. Thanks!
