### ISSUE TITLE
Plugins

### ISSUE THREAD

**Issue by julien-f** [vatesfr/xo-server#37]
- [x] Plugins are loaded at startup
- [x] Plugins can be properly unloaded or reloaded while running
- [x] Plugins can be automatically started at startup
- [x] Plugins can expose API methods
- [x] Plugins can be managed from the API
- [ ] Ideally, plugins bugs should not crash the server
- [ ] Plugins errors should be logged and retrievable from the API
- [x] `load()` / `unload()` / `configure()`, etc.

**Comment by infamy** [comment]
Will this be documented for third-party plug-ins to be written?

**Comment by julien-f** [comment]
I don't think it will in the short term because the code of xo-server changes too much.

But you are of course free to ask us if you need information and we'll do our best to help you and prevent your plugin to break :)

**Comment by olivierlambert** [comment]
@julien-f is this issue can be closed or not?

**Comment by julien-f** [comment]
Much of these are implemented, IMHO we can close this issue and open new ones as needs arise.
