### ISSUE TITLE
Handle pool master disconnection

### ISSUE THREAD

**Issue by julien-f** [vatesfr/xo-server#38]
Currently when the pool master disconnects, XO-Server attempts to reconnect a few times (10 currently, waiting 5 seconds between each tries).
If the message `HOST_IS_SLAVE` is received, it connects to the new pool master.

The problem with this implementation is that if the host never comes back up, the connection to this pool is lost, the correct approach would be to tries to connect simultaneously to all the hosts in the pool until the new pool master is known.

See https://gist.github.com/julien-f/ce23ecb6c5c185255377 for the beginning of a new implementation.

**Comment by olivierlambert** [comment]
Should be easier to do it now, thanks to https://github.com/vatesfr/xo-web/issues/234

**Comment by olivierlambert** [comment]
Done since 3.9
