### ISSUE TITLE
User delegated as admin cannot make snapshot 

### ISSUE THREAD

**Issue by buzzzo** [vatesfr/xo-server#384]
Version: server 5.1.6, web 5.1.9
type: source (not appliance)

Problem:
I've created a group with a user , and then i've created an acl with the group binded to vms, with role admin.
If i click on "snapshot" button it does nothing from the web ui.
In the logs:

4000000057c5479a0732b46c Tue, 30 Aug 2016 08:45:04 GMT xo:api luser@domain.ltd vm.snapshot(...) [10ms] =!> Unauthorized: not authenticated or not enough permissions

The user type is : user.
If i do the same thing from a full admin type account, it works

**Comment by olivierlambert** [comment]
Hi @buzzzo 

As [explained in our doc](https://xen-orchestra.com/docs/contributing.html), for all XO issues, please open a bug report here: https://github.com/vatesfr/xo-web/issues 

Plus, in your case, that's not a "bug" but more a feature. You need to give the "Operator" right to the user on the SR where are VM disks. Because creating a snapshot will need "write" permission on it.

**Comment by buzzzo** [comment]
Thx Olivier and sorry for not having read deeply the docs.
I haven't found on the docs any references regarding the sr perm for snapshot task.
Maybe will be a good time to add it ?

Thx for your help as usual.

**Comment by olivierlambert** [comment]
Yes, you are right, it's not documented! In fact the ACLs section of our doc is a bit light: https://xen-orchestra.com/docs/resources_delegation.html

That would be wonderful if you can contribute to it :)

All files are in Markdown format (which is very simple) [in this repository](https://github.com/vatesfr/xo
), and in the "docs" folder. For example, you can find the ACL file here: https://github.com/vatesfr/xo/blob/master/docs/acls.md

So feel free to fork this repository, add your stuff and upload a pull request. It's explained in the GitHub doc (you can also edit in line directly in your browser): https://help.github.com/articles/fork-a-repo/

So this way, you can explain this and probably better how to work with ACLs!
