### ISSUE TITLE
Add Job ID to backup schedules

### ISSUE THREAD

**Issue by fwsl** [vatesfr/xo-server#396]
Currently (in Backup Overview) it's hard to see which backup job from Logs corresponds to Job in Schedules. 
Easy solution: add Job ID  to Schedules part, Tag to logs, or both.

**Comment by olivierlambert** [comment]
We'll probably replace the job id by the job name, in the logs. Is it OK?

**Comment by olivierlambert** [comment]
I didn't see that you opened issues in the wrong place. As [explained in our doc](https://xen-orchestra.com/docs/contributing.html), please open issues there: https://github.com/vatesfr/xo-web/issues
