### ISSUE TITLE
Add possibility to change how date/time are presented

### ISSUE THREAD

**Issue by fwsl** [vatesfr/xo-server#397]
It would be nice to be able to change how date/time are presented.
Currently it shows: September 15, 2016, 3:00:00 AM
Add:
12/24 hour format
YYYY-mm-dd and dd-mm-YYY formats - this could be defined by user

This could also make Logs section more compact, and more readable.

**Comment by olivierlambert** [comment]
I didn't see that you opened issues in the wrong place. As [explained in our doc](https://xen-orchestra.com/docs/contributing.html), please open issues there: https://github.com/vatesfr/xo-web/issues
