### ISSUE TITLE
Not displayed server already exists

### ISSUE THREAD

**Issue by g4challenge** [vatesfr/xo-server#405]
When trying to add a server that has been configured before and removed, the following error message.

{
  "message": "server already exists",
  "stack": "Error: server already exists\n    at Servers._callee$ (/source/models/server.js:17:12)\n    at tryCatch (/usr/local/lib/node_modules/xo-server/node_modules/regenerator-runtime/runtime.js:62:40)\n    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/xo-server/node_modules/regenerator-runtime/runtime.js:336:22)\n    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/xo-server/node_modules/regenerator-runtime/runtime.js:95:21)\n    at step (/usr/local/lib/node_modules/xo-server/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)\n    at /usr/local/lib/node_modules/xo-server/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:20\n    at run (/usr/local/lib/node_modules/xo-server/node_modules/core-js/library/modules/es6.promise.js:87:22)\n    at /usr/local/lib/node_modules/xo-server/node_modules/core-js/library/modules/es6.promise.js:100:28\n    at flush (/usr/local/lib/node_modules/xo-server/node_modules/core-js/library/modules/_microtask.js:18:9)"
} 

I think the former server is still somewhere within the config, is there a proper way to delete it? The server is not shown in the web interface, therefore it can not be deleted.

**Comment by olivierlambert** [comment]
Hi g4challenge!

Thanks for the report, but it's not the good place to do that ;) As explained in [our contributing doc](https://xen-orchestra.com/docs/contributing.html), you should open a ticket here: https://github.com/vatesfr/xo-web/issues

Also, don't forget to use the MarkDown syntax for stack display (using ``` before and at the end of the block)

See you there!
