### ISSUE TITLE
Create a new SR - CIFS/SAMBA Broken

### ISSUE THREAD

**Issue by webdawg** [vatesfr/xo-server#409]
Somewhere along the line it looks like it is not passing the username and password to the xapi.call or what not.

I am not too familiar with the code and my limited knowledge right now has taken me as far as I can go.

When I try to add a SMB SR I get this:

Password entry required for 'Password for root@//host.suffix/iso_sr/:' (PID 24953).
Please enter password with the systemd-tty-ask-password-agent tool!

**Comment by olivierlambert** [comment]
You mean for a SMB ISO SR right?

I'll make tests ASAP!

**Comment by webdawg** [comment]
Yes.

Sorry about that.  I was trying to create an ISO CIFS SR.

**Comment by olivierlambert** [comment]
Sure, I'll test this. I think we never tried since 5.0, so it's probable that we missed something. Thanks for the feedback!

**Comment by olivierlambert** [comment]
@webdawg can you create the issue there? https://github.com/vatesfr/xo-web/issues/new

As explained in the contribute part of our doc, this is the place to centralize all issues (it's far better for us to manage everything at one place). Closing this here!

**Comment by webdawg** [comment]
I sure can.

**Comment by olivierlambert** [comment]
Thanks!
