### ISSUE TITLE
Add support for aliased Redis commands

### ISSUE THREAD

**Issue by bartekrutkowski** [vatesfr/xo-server#443]
When Redis is configured with certain commands aliased for security reasons (like CONFIG, SAVE and so on) xo-server fails to start properly, since DEL command is being invoked just after xo-server startds, upon user trying to log in.

The config file should accept either commands mapping or at least prefix for Redis commands.

Please, see https://github.com/bartekrutkowski/ansible-redis for more information on how such aliasing is being done and what commands are considered to be dangerous, when exposed without aliasing.

**Comment by olivierlambert** [comment]
Hi @bartekrutkowski 

Redis is not exposed outside localhost, and new XOA is even behind a firewall. The link you provided told:

> Redis security model leaves all the responsibility to the users and is very dangerous service, when exposed to the Internet without changing the default settings

But it's not the case here (not exposed).

Is aliasing still relevant in this case?

**Comment by bartekrutkowski** [comment]
@olivierlambert Thanks for prompt reply! 

I would say yes, it is still relevant, since it is still possible to use Xen Orchestra without XOA appliance, either manually, either using Ansible role https://github.com/bartekrutkowski/ansible-xen-orchestra, where Redis server is not in the same container/virtual machine/operating system as Xen Orchestra application. 

Such Redis instances are (or at least, should) be secured with AUTH password and commands aliasing, and when they are, Xen Orchestra fails to work properly, without reconfiguring Redis and lowering Redis service security.

**Comment by julien-f** [comment]
@bartekrutkowski All the Redis code is in [collection/redis.js](https://github.com/vatesfr/xo-server/blob/next-release/src/collection/redis.js), PRs are welcome :)

**Comment by olivierlambert** [comment]
I understand your point. Would you be able to contribute with a pull request?

**Comment by olivierlambert** [comment]
Damn @julien-f too fast for me.

**Comment by bartekrutkowski** [comment]
@julien-f @olivierlambert I am more than happy to contribute fixes whenever possible and share the code (hence my Ansible roles for Xen Orchestra, Redis and so on) but unfortunately JavaScript/Node language and ecosystem is not my cup of tea, so I can't be helpful here.

**Comment by julien-f** [comment]
Should be pretty simple, I'll take a quick look tomorrow.

**Comment by julien-f** [comment]
@bartekrutkowski You can now set aliased commands in [the config file](https://github.com/vatesfr/xo-server/blob/next-release/sample.config.yaml#L131-L136).

This has not been tested so tell us if you have any issues.

**Comment by bartekrutkowski** [comment]
@julien-f Thanks! I will certainly test it as soon as this code lands in a tagged release. While you're here, would it be possible to leave in the comment the list of Redis commands important to Xen Orchestra, that are on the list of potentially dangerous commands?

**Comment by julien-f** [comment]
As far as I know, only the two commands I wrote in the config file are concerned.
