### ISSUE TITLE
Error: This Fiber is not yielding

### ISSUE THREAD

**Issue by symonds** [vatesfr/xo-server#45]
Using next-release

  xo:xapi Error from root@<snip>:443: EPIPE +291ms
[WARN] <snip>: Error: write EPIPE
    at errnoException (net.js:901:11)
    at Object.afterWrite (net.js:718:19)
From previous event:
    at /root/xo-server/src/fibers-utils.coffee:77:14
From previous event:
    at /root/xo-server/src/xo.coffee:438:27
    at /root/xo-server/src/fibers-utils.coffee:82:33

/root/xo-server/src/fibers-utils.coffee:33
  results = if $isArray value
                 ^
Error: This Fiber is not yielding
    at ClientRequest.handler (/root/xo-server/src/fibers-utils.coffee:33:18)
    at ClientRequest.EventEmitter.emit (events.js:95:17)
    at CleartextStream.socketErrorListener (http.js:1547:9)
    at CleartextStream.EventEmitter.emit (events.js:95:17)
    at Socket.onerror (tls.js:1445:17)
    at Socket.EventEmitter.emit (events.js:117:20)
    at net.js:441:14
    at process._tickCallback (node.js:415:13)
root@xo:~/xo-server# 

The arrow is on the s of isArray.

**Comment by olivierlambert** [comment]
Thanks for your report!

Is this stuff triggered by something in particular, on appears just after starting `xo-server`?

**Comment by symonds** [comment]
It happens 1-5mins after starting xo-server, it is not always the same server that errors, xo-server dies completely after this error.

It may be due to the shear number of servers I have added (>100).

**Comment by olivierlambert** [comment]
Is the bug still there on `master`?

**Comment by symonds** [comment]
I didn't see it on master, however it was unable to deal with the number of servers I had added.

**Comment by olivierlambert** [comment]
Can you explain further "unable"? E.g what are the symptoms?

**Comment by symonds** [comment]
Lots of random errors such as.

Pages not being rendered correctly.
No servers being displayed.
Servers being displayed as empty.
Hugh delay in loading some pages such as settings.

This was with somewhere in the region of ~300 XenServer hosts

**Comment by olivierlambert** [comment]
Okay, it's very likely due to the number of servers and our current way we store objects in memory (VM, hosts, SR etc.)

To give you an idea, each time there is an event on a object, all the dependencies between objects lead to a full recalculation of the entire object collection.

We suspected trouble will be triggered by this implementation on bigger XO setups. Understand that's not an architecture problem, "just" an implementation one.

It will be fixed as soon we start to rewrite this piece of code for a better system.

**Comment by symonds** [comment]
Thats good news.

Currently using it to manage ~20 severs happily using the master branch and it all seems good.

**Comment by olivierlambert** [comment]
Okay, thanks for your feedback. As soon we'll start to rewrite the object collection, we'll drop news here for you to test on your huge infrastructure :)

**Comment by olivierlambert** [comment]
@symonds : can you try again with the new 4.0?

**Comment by julien-f** [comment]
Closing this issue since there will be no more fibers in the next release.

**Comment by symonds** [comment]
@olivierlambert Will be trying this over the next few weeks

**Comment by olivierlambert** [comment]
Just wait for the next minor release (4.1) coming probably next week, with some bug fixes and without fibers :)
