### ISSUE TITLE
Leverage JWTs to avoid unnecessary storage

### ISSUE THREAD

**Issue by julien-f** [vatesfr/xo-server#46]
[JSON Web Tokens](http://jwt.io/) provide a stateless way of transferring a trustable state.
The reference Node implementation is [jsonwebtoken](https://www.npmjs.com/package/jsonwebtoken).

But there still are some questions that need to be answered.

**Use with proxy requests**:
- How to ensure that a token is used only once?

**Use with session tokens**:
- How to disable/delete a token?

**Comment by olivierlambert** [comment]
@julien-f is it still relevant?

**Comment by julien-f** [comment]
It will always be relevant as it could be a nice technical approach to some problems, but this is does not address a real concern not it is a short improvement so we better close this.
