### ISSUE TITLE
Query on multiple interfaces on xva

### ISSUE THREAD

**Issue by wingZero21** [vatesfr/xo-server#48]
Hi,

Is there anyway to have multiple interfaces on the XVA as we have got it up and running but its currently unable to access our Xen Server hosts currently.

When adding the servers into the GUI it adds them but then no data is showing likely due to not being able to access the servers.

Details:
xoa-free xo-server[1296]: xo:xapi Error from root@hostname:443: ETIMEDOUT

**Comment by olivierlambert** [comment]
It tells you: the host you are try to reach do not answer.

Are you sure you can at least ping it from XOA?

**Comment by wingZero21** [comment]
Hey,

This can be closed I sorted this. I just added them in manually on the network settings.
