### ISSUE TITLE
Octal literal in strict mode

### ISSUE THREAD

**Issue by arjing** [vatesfr/xo-server#54]
OS:windows 7 
npm start

SyntaxError: D:/0work/3.8/xo-server/node_modules/schema-inspector/lib/schema-inspector.js: Octal literal in strict mode (92:61)

schema-inspector.js code：
		this._dumpStack = function () {
			return _stack.map(function (i) {return i.replace(/^\[/g, '\033\034\035\036');})
			.join('.').replace(/\.\033\034\035\036/g, '[');
		};

**Comment by julien-f** [comment]
Thanks for the report, I'm looking into it.

**Comment by julien-f** [comment]
Have you installed XO from the git repositories?

Which branch are you using? `master` or `next-release`?

**Comment by arjing** [comment]
i use version 3.8
https://github.com/vatesfr/xo-server/releases/tag/v3.8.0

**Comment by julien-f** [comment]
Unfortunately I do not have a Windows to test it right now.

What version of Node/IO.js are you using?

You may want to try the `next-release` branch which works a bit differently. Note that you will need to do a `npm run build` before `npm start`.

**Comment by julien-f** [comment]
I'm closing this as I think it should be fixed with the 3.9 release, feel free to reopen if necessary.
