### ISSUE TITLE
Fallback with "event.next" if "event.from" fails

### ISSUE THREAD

**Issue by olivierlambert** [vatesfr/xo-server#68]
Because XenServer before 6.x fails with `event.from()`. So we should be able to fallback to `event.next`.

**Comment by olivierlambert** [comment]
@julien-f : can you give me a rough estimation about the load involved to fix this?

**Comment by julien-f** [comment]
Dunno, probably 0.5-1 day.

**Comment by julien-f** [comment]
Fixed by f6e5743f20e70ae5300004bb369470ea7039e453.
