### ISSUE TITLE
When an API method returns a circurlar object, it fails to send silently

### ISSUE THREAD

**Issue by julien-f** [vatesfr/xo-server#71]
Issue detected in `scheduler.enable()`.

It seems that when a value failed to be formatted in JSON-RPC, it is discarded silently.
It should not be the case because [json-rpc-peer](julien-f/js-json-rpc-peer) should emit an `error` event.

**Comment by marsaud** [comment]
This can be reproduced easily by returning an enabled schedule (see src/scheduler.js & src/api/scheduler.js) holding a cronjob objetc
