### ISSUE TITLE
Gulp error while building

### ISSUE THREAD

**Issue by taypc6** [vatesfr/xo-server#78]
I was trying to build this on a CentOS 6.6 machine after changing the instructions provided for Debian. For CentOS, there were many other packages needed other than the ones listed, and also one that was Debian only, so that may have caused the problem as well (build-essential). However, I don't know if this error is a directly CentOS-related issue or if it's the package that I'm missing, or neither. 

There were only a few warnings in the `npm install` process, and those were:
```
npm WARN optional dep failed, continuing fsevents@0.3.8
npm WARN optional dep failed, continuing default-browser-id@1.0.2
npm WARN engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"0.12.7","npm":"2.11.3"})
npm WARN prefer global node-inspector@0.11.2 should be installed with -g
```
However as soon as npm run build was started, these errors popped up
```
> xo-server@4.3.2 prepublish /etc/xo-server
> npm run build


> xo-server@4.3.2 build /etc/xo-server
> gulp build --production

[14:32:19] Using gulpfile /etc/xo-server/gulpfile.js
[14:32:19] Starting 'build'...
[14:32:19] Starting 'buildCoffee'...
[14:32:19] Starting 'buildEs6'...
[14:32:25] Finished 'buildCoffee' after 5.45 s
[14:32:25] 'buildEs6' errored after 5.51 s
[14:32:25] SyntaxError in plugin 'gulp-babel'
Message:
    /etc/xo-server/src/decorators.spec.js: Unexpected token (13:4)
[14:32:25] 'build' errored after 5.54 s
[14:32:25] SyntaxError in plugin 'gulp-babel'
Message:
    /etc/xo-server/src/decorators.spec.js: Unexpected token (13:4)
```

Contents of npm-debug.log in the xo-server folder
```
 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@2.11.3
3 info using node@v0.12.7
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info prebuild xo-server@4.3.2
6 info build xo-server@4.3.2
7 verbose unsafe-perm in lifecycle true
8 info xo-server@4.3.2 Failed to exec build script
9 verbose stack Error: xo-server@4.3.2 build: `gulp build --production`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
9 verbose stack     at EventEmitter.emit (events.js:110:17)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at ChildProcess.emit (events.js:110:17)
9 verbose stack     at maybeClose (child_process.js:1015:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
10 verbose pkgid xo-server@4.3.2
11 verbose cwd /etc/xo-server
12 error Linux 2.6.32-504.30.3.el6.x86_64
13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
14 error node v0.12.7
15 error npm  v2.11.3
16 error code ELIFECYCLE
17 error xo-server@4.3.2 build: `gulp build --production`
17 error Exit status 1
18 error Failed at the xo-server@4.3.2 build script 'gulp build --production'.
18 error This is most likely a problem with the xo-server package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     gulp build --production
18 error You can get their info via:
18 error     npm owner ls xo-server
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```

**Comment by julien-f** [comment]
I cannot reproduce neither on master or on next-release…

Which branch are you using?

**Comment by taypc6** [comment]
I was using the master. I have never used n or npm before, so I don't know if I'm missing a dependency or not. Also, could SELinux cause a problem like this? I'll try this again with a completely clean CentOS 6.6 machine and see if the error resolves itself.

**Comment by julien-f** [comment]
I don't think you are missing deps otherwise npm would have scream much louder, these are just warnings and optional dependencies are obviously not required, there are often present to provide better perfs or missing functionalities in previous version of Node.

As for SELinux I have no idea…

**Comment by julien-f** [comment]
The error looked like it originated for Babel, maybe a bug has been introduced and fixed ever since, so IMHO, you should try reinstalling Node dependencies (ie remove the node_modules directory and npm install again) before doing any heavy work.

**Comment by taypc6** [comment]
The server works now, and the error was apparently me putting the file in etc. Once I tried building it in the home directory, it worked fine, not a single error. Turning off SELinux made no difference to the etc errors, and this particular machine was running the process as root, so there weren't any permission errors. It worked on both the machine that wasn't working  before and a brand new one.

**Comment by olivierlambert** [comment]
\o/
