### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by xudaiqing** [vatesfr/xo-server#88]
I install xo-server from source follow https://github.com/vatesfr/xo/blob/master/doc/installation/README.md and find it got killed because out of memory after several days.
monitor it use pm2 shows a steady climb in memory with no operation.
![xo](https://cloud.githubusercontent.com/assets/3690727/9985752/b74d8b46-6064-11e5-8b79-19b592b0ab12.PNG)

I current installed 4.5.0 on debian 7.9. Node version is 0.12.7.

**Comment by olivierlambert** [comment]
Could you try with the latest stable version of `node`?

**Comment by xudaiqing** [comment]
You mean node 4.1.0?

**Comment by xudaiqing** [comment]
I have reinstall pm2 and all the npm packages with node 4.1.0. Will report result tomorrow.

**Comment by olivierlambert** [comment]
Thanks @xudaiqing !

**Comment by xudaiqing** [comment]
it's under controll in 4.1.0.
![xo](https://cloud.githubusercontent.com/assets/3690727/10009359/0bd414b0-610e-11e5-8971-843de799cb31.PNG)
